server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://localhost:8081
          predicates:
            - Path=/cleaningReservations/** 
        - id: Cleaning
          uri: http://localhost:8082
          predicates:
            - Path=/cleans/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: DashBoard
          uri: http://localhost:8084
          predicates:
            - Path= /dashBoardViews/**
        - id: Message
          uri: http://localhost:8085
          predicates:
            - Path=/messages/** 
        - id: Paymethod
          uri: http://localhost:8086
          predicates:
            - Path=/paymethods/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/cleaningReservations/** 
        - id: Cleaning
          uri: http://Cleaning:8080
          predicates:
            - Path=/cleans/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: DashBoard
          uri: http://DashBoard:8080
          predicates:
            - Path= /dashBoardViews/**
        - id: Message
          uri: http://Message:8080
          predicates:
            - Path=/messages/** 
        - id: Paymethod
          uri: http://Paymethod:8080
          predicates:
            - Path=/paymethods/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
