apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cleaning
  labels:
    app: Cleaning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Cleaning
  template:
    metadata:
      labels:
        app: Cleaning
    spec:
      containers:
        - name: Cleaning
          image: username/Cleaning:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5